baseURL = "https://devdalgic.github.io"
languageCode = "en-us"
title = "Denizhan Dalgıç"
theme = "toha"
enableEmoji = true

[languages.en]
languageName = "English"
weight = 1

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
background = "/images/site/background.jpg"
gitRepo = "https://github.com/hugo-toha/hugo-toha.github.io"
gitBranch = "main"
enableTOC = true
enableTags = true
showFlags = true

  [params.logo]
  main = "/images/author/small2.jpg"
  inverted = "/images/author/small2.jpg"
  favicon = "/images/author/small2.jpg"

  [params.topNavbar]
  maxVisibleSections = 8

  [params.darkMode]
  provider = "darkreader"
  enable = true
  default = "system"

[params.features.portfolio]
enable = false

[params.features.blog]
enable = false

  [params.features.blog.shareButtons]
  facebook = true
  twitter = true
  linkedin = true
  reddit = true
  whatsapp = true
  email = true

[params.features.notes]
enable = false

[params.features.comment]
enable = false

  [params.features.comment.disqus]
  shortName = "toha-example-site"

[params.features.analytics]
enabled = false

  [params.features.analytics.google]
  id = "G-H4LBG7NDFZ"

  [params.footer]
  enable = true
  template = "footer.html"

    [params.footer.navigation]
    enable = false
    customMenus = true

    [params.footer.contactMe]
    enable = false

    [params.footer.credentials]
    enable = true

    [params.footer.newsletter]
    enable = false
    provider = "mailchimp"
    mailchimpURL = "https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e"

    [params.footer.disclaimer]
    enable = false
